package com.aranmakina.backend.model;

public enum CategoryType {
    SABIT_ASKILI_ZINCRLI_VINC,
    MANUEL_SARYOLU_ZINCRLI_VINC,
    MONORAY_ZINCRLI_VINC,
    SABIT_HALATLI_VINC,
    MANUEL_SARYOLU_HALATLI_VINC,
    MONORAY_HALATLI_VINC,
    IRGAT_VINC,
    MINI_VINC,
    TRANSPALET,
    MEKANIK_CARASKAL,
    SARYO,
    MAKARA,
    KUMANDA
}
